# Generated by Django 4.1.2 on 2022-10-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=30)),
                ("preco", models.FloatField(max_length=10)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("SW", "Star Wars"),
                            ("C", "Console"),
                            ("D", "Diversos"),
                        ],
                        default="D",
                        max_length=3,
                    ),
                ),
                ("url", models.CharField(max_length=100)),
                ("descricao", models.TextField(max_length=500)),
            ],
        ),
    ]
