# Generated by Django 4.1.2 on 2022-10-12 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alurageek", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("senha", models.CharField(max_length=13)),
                ("admin", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="produtos",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="alurageek.users",
            ),
        ),
    ]
