# Generated by Django 4.1.2 on 2022-10-12 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alurageek", "0002_users_produtos_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="produtos", name="user",),
        migrations.DeleteModel(name="Users",),
    ]
