# Generated by Django 4.1.2 on 2022-10-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alurageek", "0003_remove_produtos_user_delete_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("senha", models.CharField(max_length=13)),
                ("admin", models.BooleanField(default=False)),
            ],
        ),
    ]
