# Generated by Django 4.1.2 on 2022-10-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alurageek", "0005_produtos_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="descricao",
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name="produtos", name="url", field=models.CharField(max_length=500),
        ),
    ]
